2698

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -44,10 +44,84 @@ AC_ARG_ENABLE(
 	[packetver],
 	AC_HELP_STRING(
 		[--enable-packetver=ARG],
-		[Sets the PACKETVER define of the map-server. (see src/map/clif.h)]
+		[Sets the PACKETVER define. (see src/common/mmo.h)]
 	),
 	[enable_packetver="$enableval"],
 	[enable_packetver=""]
+)
+
+
+#
+# packetver-RE
+#
+AC_ARG_ENABLE(
+	[packetver-re],
+	AC_HELP_STRING(
+		[--disable-packetver-re],
+		[Sets or unsets the PACKETVER_RE define - see src/common/mmo.h (currently enabled by default)]
+	),
+	[
+		enable_packetver_re="$enableval"
+		case $enableval in
+			"no");;
+			"yes");;
+			*) AC_MSG_ERROR([[invalid argument --enable-packetver-re=$enableval... stopping]]);;
+		esac
+	],
+	[enable_packetver_re="yes"]
+)
+
+
+#
+# Obfuscation keys
+#
+AC_ARG_WITH(
+	[key1],
+	AC_HELP_STRING(
+		[--with-key1@<:@=ARG@:>@],
+		[Set the first obfuscation key (ignored unless the other two are also specified)]
+	),
+	[
+		obfuscationkey1="$( expr "0x$withval" : '0*x*\(0x@<:@A-Fa-f0-9@:>@\{8\}\)' )"
+		if ! expr "x$obfuscationkey1" : 'x0x@<:@A-Fa-f0-9@:>@\{8\}' >/dev/null 2>&1; then
+			obfuscationkey1=""
+		fi
+	],
+	[
+		obfuscationkey1=""
+	]
+)
+AC_ARG_WITH(
+	[key2],
+	AC_HELP_STRING(
+		[--with-key2@<:@=ARG@:>@],
+		[Set the second obfuscation key (ignored unless the other two are also specified)]
+	),
+	[
+		obfuscationkey2="$( expr "0x$withval" : '0*x*\(0x@<:@A-Fa-f0-9@:>@\{8\}\)' )"
+		if ! expr "x$obfuscationkey2" : 'x0x@<:@A-Fa-f0-9@:>@\{8\}' >/dev/null 2>&1; then
+			obfuscationkey2=""
+		fi
+	],
+	[
+		obfuscationkey2=""
+	]
+)
+AC_ARG_WITH(
+	[key3],
+	AC_HELP_STRING(
+		[--with-key3@<:@=ARG@:>@],
+		[Set the third obfuscation key (ignored unless the other two are also specified)]
+	),
+	[
+		obfuscationkey3="$( expr "0x$withval" : '0*x*\(0x@<:@A-Fa-f0-9@:>@\{8\}\)' )"
+		if ! expr "x$obfuscationkey3" : 'x0x@<:@A-Fa-f0-9@:>@\{8\}' >/dev/null 2>&1; then
+			obfuscationkey3=""
+		fi
+	],
+	[
+		obfuscationkey3=""
+	]
 )
 
 
@@ -110,8 +184,12 @@ AC_ARG_ENABLE(
 		
 			Note:
 				Please ensure that you've disabled dynamic CPU-Frequencys, such as power saving options.
-				(On the most modern Dedicated Servers cpufreq is preconfigured, see your distribution's manual
-				 how to disable it)
+				(On most modern Dedicated Servers cpufreq is preconfigured, see your distribution's
+				 manual how to disable it).
+				Furthermore, If your CPU has built-in CPU-Frequency scaling features (such as Intel's
+				 SpeedStep(R)), do not enable this option. Recent CPUs (Intel Core or newer) guarantee
+				 a fixed increment rate for their TSC, so it should be safe to use, but please doublecheck
+				 the documentation of both your CPU and OS before enabling this option.
 		]
 	),
 	[
@@ -168,22 +246,45 @@ AC_ARG_ENABLE(
 # LTO
 #
 AC_ARG_ENABLE(
-    [lto],
-    AC_HELP_STRING(
-        [--enable-lto],
-        [
+	[lto],
+	AC_HELP_STRING(
+		[--enable-lto],
+		[
 			Enables or Disables Linktime Code Optimization (LTO is enabled by default)
-        ]
-    ),
-    [
-        enable_lto="$enableval"
-        case $enableval in
-            "no");;
-            "yes");;
-            *) AC_MSG_ERROR([[invalid argument --enable-lto=$disableval... stopping]]);;
-        esac
-    ],
-    [enable_lto="yes"]
+		]
+	),
+	[
+		enable_lto="$enableval"
+		case $enableval in
+			"no");;
+			"yes");;
+			*) AC_MSG_ERROR([[invalid argument --enable-lto=$disableval... stopping]]);;
+		esac
+	],
+	[enable_lto="yes"]
+)
+
+
+#
+# Renewal
+#
+AC_ARG_ENABLE(
+	[renewal],
+	AC_HELP_STRING(
+		[--disable-renewal],
+		[
+			Disable Ragnarok Renewal support (override settings in src/config/renewal.h)
+		]
+	),
+	[
+		enable_renewal="$enableval"
+		case $enableval in
+			"no");;
+			"yes");;
+			*) AC_MSG_ERROR([[invalid argument --enable-renewal=$enableval... stopping]]);;
+		esac
+	],
+	[enable_renewal="yes"]
 )
 
 
@@ -330,7 +431,7 @@ AC_PATH_PROG(AR, ar)
 AC_LANG([C])
 
 
-CFLAGS="$CFLAGS -pipe -ffast-math -Wall -Wno-sign-compare"
+CFLAGS="$CFLAGS -pipe -ffast-math -Wall -Wextra -Wno-sign-compare"
 CPPFLAGS="$CPPFLAGS -I../common"
 
 
@@ -414,19 +515,6 @@ AC_RUN_IFELSE(
 )
 
 
-AC_MSG_CHECKING([whether $CC supports -Wno-unused-parameter])
-OLD_CFLAGS="$CFLAGS"
-CFLAGS="$CFLAGS -Wno-unused-parameter"
-AC_COMPILE_IFELSE(
-	[int foo;],
-	[AC_MSG_RESULT([yes])],
-	[
-		AC_MSG_RESULT([no])
-		CFLAGS="$OLD_CFLAGS"
-	]
-)
-
-
 #
 # LTO Support test
 #
@@ -460,49 +548,141 @@ if test "$enable_lto" != "no" ; then
 fi
 
 
-
-AC_MSG_CHECKING([whether $CC supports -Wno-pointer-sign])
-OLD_CFLAGS="$CFLAGS"
-CFLAGS="$CFLAGS -Wno-pointer-sign"
-AC_COMPILE_IFELSE(
-	[int foo;],
+AC_DEFUN(AC_CHECK_COMPILER_WFLAG,
 	[
-		AC_MSG_RESULT([yes])
-		AC_MSG_CHECKING([whether $CC can actually use -Wno-pointer-sign])
-		# This option causes warnings in C++ mode
-		# Note: -Werror must be before -Wno-pointer-sign, otherwise it does not do anything
-		CFLAGS="$OLD_CFLAGS -Werror -Wno-pointer-sign"
+		AC_MSG_CHECKING([whether $CC supports -W$1])
+		OLD_CFLAGS="$CFLAGS"
+		CFLAGS="$CFLAGS -Werror -W$1"
 		AC_COMPILE_IFELSE(
-			[int foo;],
+			[AC_LANG_SOURCE([int foo;])],
 			[
 				AC_MSG_RESULT([yes])
-				CFLAGS="$OLD_CFLAGS -Wno-pointer-sign"
+				CFLAGS="$OLD_CFLAGS -W$1"
+				# Optionally, run a test
+				if test "x$2" != "x"; then
+					AC_MSG_CHECKING([whether $CC can actually use -W$1])
+					CFLAGS="$OLD_CFLAGS -Werror -W$1"
+					AC_COMPILE_IFELSE(
+						[AC_LANG_SOURCE([$2])],
+						[
+							AC_MSG_RESULT([no])
+							CFLAGS="$OLD_CFLAGS"
+						]
+						[
+							AC_MSG_RESULT([yes])
+							CFLAGS="$OLD_CFLAGS -W$1"
+						],
+					)
+				fi
 			],
 			[
 				AC_MSG_RESULT([no])
 				CFLAGS="$OLD_CFLAGS"
 			]
 		)
-	],
-	[
-		AC_MSG_RESULT([no])
-		CFLAGS="$OLD_CFLAGS"
 	]
 )
 
-
-AC_MSG_CHECKING([whether $CC supports -Wno-switch])
-OLD_CFLAGS="$CFLAGS"
-CFLAGS="$CFLAGS -Wno-switch"
-AC_COMPILE_IFELSE(
-	[int foo;],
-	[AC_MSG_RESULT([yes])],
+AC_DEFUN(AC_CHECK_COMPILER_WNOFLAG,
 	[
-		AC_MSG_RESULT([no])
-		CFLAGS="$OLD_CFLAGS"
+		AC_MSG_CHECKING([whether $CC supports -Wno-$1])
+		OLD_CFLAGS="$CFLAGS"
+		CFLAGS="$CFLAGS -Werror -Wno-$1"
+		AC_COMPILE_IFELSE(
+			[AC_LANG_SOURCE([int foo;])],
+			[
+				# Recent versions of gcc don't fail if -Wno-foo is not recognized
+				# (unless there are also other warnings), so we also check for -Wfoo
+				# which always fails if not supported
+				CFLAGS="$OLD_CFLAGS -Werror -W$1"
+				AC_COMPILE_IFELSE(
+					[AC_LANG_SOURCE([int foo;])],
+					[
+						AC_MSG_RESULT([yes])
+						CFLAGS="$OLD_CFLAGS -Wno-$1"
+						# Optionally, run a test
+						if test "x$2" != "x"; then
+							AC_MSG_CHECKING([whether $CC can actually use -Wno-$1])
+							CFLAGS="$OLD_CFLAGS -Werror -W$1"
+							AC_COMPILE_IFELSE(
+								[AC_LANG_SOURCE([$2])],
+								[
+									AC_MSG_RESULT([not needed but enabled])
+									CFLAGS="$OLD_CFLAGS"
+								],
+								[
+									CFLAGS="$OLD_CFLAGS -Werror -Wno-$1"
+									AC_COMPILE_IFELSE(
+										[AC_LANG_SOURCE([$2])],
+										[
+											AC_MSG_RESULT([yes])
+											CFLAGS="$OLD_CFLAGS -Wno-$1"
+										],
+										[
+											AC_MSG_RESULT([no])
+											CFLAGS="$OLD_CFLAGS"
+										]
+									)
+								]
+							)
+						fi
+					],
+					[
+						AC_MSG_RESULT([no])
+						CFLAGS="$OLD_CFLAGS"
+					]
+				)
+			],
+			[
+				AC_MSG_RESULT([no])
+				CFLAGS="$OLD_CFLAGS"
+			]
+		)
 	]
 )
 
+AC_CHECK_COMPILER_WNOFLAG(unused-parameter, [int foo(int bar) { return 0; }])
+AC_CHECK_COMPILER_WNOFLAG(maybe-uninitialized)
+AC_CHECK_COMPILER_WNOFLAG(clobbered)
+AC_CHECK_COMPILER_WFLAG(empty-body)
+AC_CHECK_COMPILER_WFLAG(newline-eof)
+AC_CHECK_COMPILER_WFLAG(int-conversion)
+AC_CHECK_COMPILER_WFLAG(enum-conversion)
+AC_CHECK_COMPILER_WFLAG(shorten-64-to-32)
+AC_CHECK_COMPILER_WFLAG(constant-conversion)
+AC_CHECK_COMPILER_WFLAG(bool-conversion)
+AC_CHECK_COMPILER_WNOFLAG(switch)
+AC_CHECK_COMPILER_WNOFLAG(missing-field-initializers)
+
+# Certain versions of gcc make -Wshadow completely useless by making it flood
+# you with unnecessary warnings <https://lkml.org/lkml/2006/11/28/239>
+# Let's check if we can really use it
+SAVED_OLD_CFLAGS="$CFLAGS"
+AC_CHECK_COMPILER_WFLAG(shadow)
+if test "x$CFLAGS" != "x$SAVED_OLD_CFLAGS"; then
+	AC_MSG_CHECKING([whether $CC can efficiently use -Wshadow])
+	NEW_CFLAGS="$CFLAGS"
+	CFLAGS="$CFLAGS -Werror -Wshadow"
+	AC_COMPILE_IFELSE(
+		[AC_LANG_SOURCE([
+			int foo(void) {
+				return 0;
+			}
+			int bar(void) {
+				int foo = 0;
+				return foo + 1;
+			}
+		])],
+		[
+			AC_MSG_RESULT([yes])
+			CFLAGS="$NEW_CFLAGS"
+		],
+		[
+			AC_MSG_RESULT([no])
+			CFLAGS="$SAVED_OLD_CFLAGS"
+		]
+	)
+fi
 
 AC_MSG_CHECKING([whether $CC supports -fPIC])
 OLD_CFLAGS="$CFLAGS"
@@ -596,6 +776,24 @@ if test -n "$enable_packetver" ; then
 	CFLAGS="$CFLAGS -DPACKETVER=$enable_packetver"
 fi
 
+#
+# Packetver-RE
+#
+case $enable_packetver_re in
+	"yes")
+		# default value
+		CFLAGS="$CFLAGS -DDISABLE_PACKETVER_RE"
+		;;
+	"no")
+		;;
+esac
+
+#
+# Obfuscation keys
+#
+if test -n "$obfuscationkey1" -a -n "$obfuscationkey2" -a -n "$obfuscationkey3"; then
+	CFLAGS="$CFLAGS -DOBFUSCATIONKEY1=$obfuscationkey1 -DOBFUSCATIONKEY2=$obfuscationkey2 -DOBFUSCATIONKEY3=$obfuscationkey3"
+fi
 
 #
 # Debug
@@ -603,7 +801,7 @@ fi
 case $enable_debug in
 	"no")
 		# default value
-		CFLAGS="$CFLAGS -Wno-unused -Wno-parentheses"
+#		CFLAGS="$CFLAGS -Wno-unused -Wno-parentheses"
 		;;
 	"yes")
 		CFLAGS="$CFLAGS -g -DDEBUG"
@@ -651,6 +849,17 @@ case $enable_profiler in
 		;;
 esac
 
+#
+# Renewal
+#
+case $enable_renewal in
+	"no")
+		CFLAGS="$CFLAGS -DDISABLE_RENEWAL"
+		;;
+	"yes")
+		# default value
+		;;
+esac
 
 #
 # zlib library (required)
@@ -842,7 +1051,7 @@ esac
 AC_SUBST([DLLEXT])
 
 AC_MSG_CHECKING([for MinGW])
-if test -n "`$CC --version | grep -i mingw`" ; then
+if test -n "`$CC --version 2>/dev/null | grep -i mingw`" ; then
 	AC_MSG_RESULT([yes])
 	CPPFLAGS="$CPPFLAGS -DMINGW"
 	if test -z "$fd_setsize" ; then
